image:
  registry: $MYSQL_REGISTRY
metrics:
  image:
    registry: $MYSQL_REGISTRY
db:
  name: e2edb
  password: e2edb
  user: e2edb
replication:
  enabled: false
root:
  password: e2edb
primary:
  livenessProbe:
    enabled: false
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1