#@ load("@ytt:data", "data")

ingress:
  enabled: true
  certManager: false
  pathType: ImplementationSpecific
  apiVersion:
  hostname: #@ "kibana.{}".format(data.values.ingress.domain)
  path: /
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: contour
    kubernetes.io/tls-acme: "true"
  tls: true
  elasticsearch:
    tls: false
    hosts:
      - elasticsearch-elasticsearch-data
    port: 9200