#@ load("@ytt:data", "data")

expose:
  ingress:
    hosts:
      core: #@ "harbor.{}".format(data.values.ingress.domain)
persistence:
  resourcePolicy: ""
  persistentVolumeClaim:
    registry:
      existingClaim: "harbor-registry-pvc"
notary:
  enabled: false
externalURL: #@ "https://harbor.{}".format(data.values.ingress.domain)
harborAdminPassword: #@ data.values.harbor.adminPassword
