#@ load("@ytt:data", "data")

concourse:
  web:
    externalUrl: #@ "https://concourse.{}".format(data.values.ingress.domain)
    auth:
      mainTeam:
        localUser: #@ data.values.concourse.username
web:
  ingress:
    enabled: true
    hosts: #@ ["concourse.{}".format(data.values.ingress.domain)]
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-staging
      ingress.kubernetes.io/force-ssl-redirect: "true"
      kubernetes.io/ingress.class: contour
      kubernetes.io/tls-acme: "true"
secrets:
  localUsers: #@ "{}:{}".format(data.values.concourse.username,data.values.concourse.password)
