#@ load("@ytt:data", "data")

concourse:
  web:
    externalUrl: #@ "https://concourse.{}".format(data.values.ingress.domain)
    auth:
      mainTeam:
        localUser: #@ data.values.concourse.username
web:
  ingress:
    enabled: true
    hosts: #@ ["concourse.{}".format(data.values.ingress.domain)]
    tls:
    - secretName: #@ "{}/{}".format(data.values.ingress.contour_tls_namespace,data.values.ingress.contour_tls_secret)
      hosts: #@ ["concourse.{}".format(data.values.ingress.domain)]
secrets:
  localUsers: #@ "{}:{}".format(data.values.concourse.username,data.values.concourse.password)
