#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@overlay/match by=overlay.subset({"kind":"Ingress"}),expects="0+"
---
spec:
  rules:
    host:
      paths:
      #@overlay/match missing_ok=True
      - path: "/"
        pathType: "Prefix"